---
- name: Build EE environments
  include_tasks: 00_build_ee.yml
  loop: "{{ ee_list }}"
  loop_control:
    loop_var: __execution_environment_definition

- name: Create execution environment definition file
  ansible.builtin.template:
    src: ee_controller.yaml.j2
    dest: "/tmp/ee_controller.yaml"
    mode: '0644'
  delegate_to: localhost

- name: Include templated variable
  ansible.builtin.include_vars:
    file: "/tmp/ee_controller.yaml"
  delegate_to: localhost

- name: Display templated variables
  ansible.builtin.debug:
    var: controller_execution_environments

- name: Set stats for use in another workflow node
  ansible.builtin.set_stats:
    data:
      controller_execution_environments: "{{ controller_execution_environments }}"
...
