---
galaxy_info:
  author: Sean Sullivan
  description: Excecution enviroment builder
  company: Red Hat

  license: GPL-3.0-or-later

  min_ansible_version: 2.14.0
  platforms:
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - all

  galaxy_tags: []

dependencies: []
...
