---
name: Run Test of EE utilities
on: [push]

permissions:
  contents: read

jobs:
  Integration-test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.x'

      - name: Install podman
        run: sudo apt -y install podman

      - name: Install Ansible and Ansible Builder
        run: pip install --upgrade setuptools ansible-core ansible-builder

      - name: Move ansible.cfg to root
        run: mv .github/files/ansible.cfg .

      - name: Install Dependencies
        run: ansible-galaxy collection install infra.ee_utilities containers.podman -f

      - name: podman login
        run: podman login quay.io --username redhat_cop+github_action --password ${{ secrets.quay_token }}

      - name: Build EE
        run: ansible-playbook .github/tests/build_ee.yml -e "ee_registry_username=redhat_cop+github_action" -e "ee_registry_password=${{ secrets.quay_token }}" --connection=local -e "ee_registry_dest=quay.io/redhat_cop/config_as_code_ee" -vvv
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
...
