---
# This workflow action will run pre-commit, which will execute ansible and yaml linting
# See .pre-commit-config.yml for what hooks are executed
name: Yaml and Ansible Lint

on:
  schedule:
    - cron: "0 5 * * *"
  push:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Collections
        run: |
          sudo apt install software-properties-common
          pip install --upgrade ansible
      - uses: pre-commit/action@v2.0.0
...
