---
# This workflow action will run pre-commit, which will execute ansible and yaml linting
# See .pre-commit-config.yaml for what hooks are executed
name: Update pre-commit configuration


on:
  schedule:
    - cron: "0 5 * * *"

jobs:
  pre-commit:
    uses: "redhat-cop/ansible_collections_tooling/.github/workflows/update_precommit.yml@main"
    with:
      github_actor: ${{ github.actor }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
...
